alter table activity 
add   `activity_hpd` float unsigned NOT NULL,
add  `activity_visiters_total` int(10) DEFAULT NULL,
add  `activity_cadres` varchar(30) DEFAULT NULL;
-- ------------------------------------
alter table activity_facilitator add `facilitator_topic` varchar(100) DEFAULT NULL;
-- ---------------------------------------
alter table activity_facilitator_staging 
	add `facilitator_topic` varchar(100) DEFAULT NULL,
	Add `facilitator_activity_id` INT( 11 ) NULL DEFAULT NULL,
	ADD `facilitator_custom` LONGTEXT NULL DEFAULT NULL;
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS `admission_caregivers` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `fname` varchar(100) DEFAULT NULL,
  `lname` varchar(100) DEFAULT NULL,
  `age` varchar(10) DEFAULT NULL,
  `health_status` tinyint(1) unsigned DEFAULT '0',
  `marital_status` tinyint(2) unsigned DEFAULT '0',
  `educ_level` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `employment` tinyint(2) unsigned NOT NULL DEFAULT '0',
  `idno` varchar(100) NOT NULL DEFAULT '',
  `mobile` varchar(50) NOT NULL DEFAULT '',
  `client_id` int(11) unsigned NOT NULL,
  `reason` tinyint(2) unsigned DEFAULT NULL,
  `datesoff` date DEFAULT NULL,
  `role` enum('mother','father','pri','sec') DEFAULT NULL,
  `relationship` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `client_id` (`client_id`),
  KEY `role` (`role`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 COMMENT='admission_caregivers';
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS `admission_info_slim` (
  `admission_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `admission_client_id` int(10) unsigned NOT NULL,
  `admission_staff_id` int(11) unsigned DEFAULT '0',
  `admission_chw` int(11) unsigned DEFAULT NULL,
  `admission_clinic_id` int(11) unsigned DEFAULT NULL,
  `admission_dob` date DEFAULT NULL,
  `admission_age_yrs` double DEFAULT NULL,
  `admission_age_months` double DEFAULT NULL,
  `admission_age_status` tinyint(1) unsigned DEFAULT NULL,
  `admission_gender` enum('1','2') DEFAULT NULL,
  `admission_residence` varchar(150) DEFAULT NULL,
  `admission_location` int(11) unsigned DEFAULT NULL,
  `admission_entry_date` date DEFAULT NULL,
  `admission_school_level` tinyint(2) unsigned DEFAULT NULL,
  `admission_reason_not_attending` tinyint(2) unsigned DEFAULT NULL,
  `admission_reason_not_attending_notes` varchar(100) DEFAULT '',
  `admission_total_orphan` tinyint(1) unsigned DEFAULT NULL,
  `admission_province` varchar(100) DEFAULT '',
  `admission_district` varchar(100) DEFAULT '',
  `admission_village` varchar(100) DEFAULT '',
  `admission_father` int(11) unsigned DEFAULT NULL,
  `admission_father_status` tinyint(2) unsigned DEFAULT NULL,
  `admission_father_raising_child` enum('1','2') DEFAULT NULL,
  `admission_mother` int(11) unsigned DEFAULT NULL,
  `admission_mother_status` tinyint(2) unsigned DEFAULT NULL,
  `admission_mother_raising_child` enum('1','2') DEFAULT NULL,
  `admission_caregiver_pri` int(11) unsigned DEFAULT NULL,
  `admission_caregiver_pri_relationship` varchar(100) DEFAULT NULL,
  `admission_caregiver_sec` int(11) unsigned NOT NULL,
  `admission_caregiver_sec_relationship` varchar(100) NOT NULL,
  `admission_family_income` int(11) DEFAULT NULL,
  `admission_risk_level` tinyint(1) unsigned DEFAULT NULL,
  `admission_risk_level_description` text,
  `admission_notes` text,
  `admission_custom` longtext,
  `admission_enclosures` varchar(20) DEFAULT NULL,
  `admission_birth_cert` varchar(50) DEFAULT NULL,
  `admission_id_no` varchar(50) DEFAULT NULL,
  `admission_med_recs` tinyint(1) DEFAULT NULL,
  `admission_nhf` varchar(50) DEFAULT NULL,
  `admission_immun` varchar(50) DEFAULT NULL,
  `admission_death_cert` varchar(50) DEFAULT NULL,
  `admission_enclosures_other` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`admission_id`),
  UNIQUE KEY `admission_id` (`admission_id`),
  KEY `client_clinic_id` (`admission_client_id`,`admission_clinic_id`),
  KEY `client_staff_id` (`admission_client_id`,`admission_staff_id`),
  KEY `client_dob` (`admission_dob`),
  KEY `admission_entry_date` (`admission_entry_date`),
  KEY `admission_staff_id` (`admission_id`,`admission_staff_id`),
  KEY `admission_client_id` (`admission_client_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1;
-- -----------------------------------------------
alter table admission_info
add `admission_chw` int(11) unsigned DEFAULT NULL,
add   `admission_father` int(11) unsigned DEFAULT NULL,
change  `admission_father_status` `admission_father_status` tinyint(2) unsigned DEFAULT NULL,
change  `admission_father_raising_child` `admission_father_raising_child` enum('1','2') DEFAULT NULL,
add  `admission_mother` int(11) unsigned DEFAULT NULL,
change  `admission_mother_status` `admission_mother_status` tinyint(2) unsigned DEFAULT NULL,
change  `admission_mother_raising_child` `admission_mother_raising_child` enum('1','2') DEFAULT NULL,
add  `admission_caregiver_pri` int(11) unsigned DEFAULT NULL,
add  `admission_caregiver_pri_relationship` varchar(100) DEFAULT NULL,
add  `admission_caregiver_sec` int(11) unsigned NOT NULL,
add  `admission_caregiver_sec_relationship` varchar(100) NOT NULL,
add `admission_enclosures` varchar(20) DEFAULT NULL,
add  `admission_birth_cert` varchar(50) DEFAULT NULL,
add  `admission_id_no` varchar(50) DEFAULT NULL,
add  `admission_med_recs` tinyint(1) DEFAULT NULL,
add  `admission_nhf` varchar(50) DEFAULT NULL,
add  `admission_immun` varchar(50) DEFAULT NULL,
add  `admission_death_cert` varchar(50) DEFAULT NULL,
add  `admission_enclosures_other` varchar(200) DEFAULT NULL;
-- -----------------------------------------
alter table admission_staging
add `admission_chw` int(11) unsigned DEFAULT NULL,
add   `admission_father` int(11) unsigned DEFAULT NULL,
add  `admission_mother` int(11) unsigned DEFAULT NULL,
add  `admission_caregiver_pri` int(11) unsigned DEFAULT NULL,
add  `admission_caregiver_pri_relationship` varchar(100) DEFAULT NULL,
add  `admission_caregiver_sec` int(11) unsigned NOT NULL,
add  `admission_caregiver_sec_relationship` varchar(100) NOT NULL,
add `admission_enclosures` varchar(20) DEFAULT NULL,
add  `admission_birth_cert` varchar(50) DEFAULT NULL,
add  `admission_id_no` varchar(50) DEFAULT NULL,
add  `admission_med_recs` tinyint(1) DEFAULT NULL,
add  `admission_nhf` varchar(50) DEFAULT NULL,
add  `admission_immun` varchar(50) DEFAULT NULL,
add  `admission_death_cert` varchar(50) DEFAULT NULL,
add  `admission_enclosures_other` varchar(200) DEFAULT NULL;
-- ---------------------------------------
alter table caregiver_client
add `caregiver_role` enum('pri','sec') NOT NULL DEFAULT 'pri',
add  `caregiver_active` enum('0','1') NOT NULL DEFAULT '1',
add  `caregiver_off` date DEFAULT NULL;
-- -----------------------------------------
CREATE TABLE IF NOT EXISTS `cbc_info` (
  `cbc_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `cbc_client_id` int(11) DEFAULT NULL,
  `cbc_name` varchar(100) DEFAULT NULL,
  `cbc_village` varchar(100) DEFAULT NULL,
  `cbc_center_id` int(10) DEFAULT NULL,
  `cbc_location` varchar(100) DEFAULT NULL,
  `cbc_entry_date` date DEFAULT NULL,
  `cbc_adm_no` varchar(30) DEFAULT NULL,
  `cbc_old` tinyint(1) DEFAULT NULL,
  `cbc_sex` tinyint(1) DEFAULT NULL,
  `cbc_age` varchar(10) DEFAULT NULL,
  `cbc_hbcare` varchar(50) DEFAULT NULL,
  `cbc_adh_support` tinyint(1) DEFAULT NULL,
  `cbc_remarks` text,
  `cbc_refers` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`cbc_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;
-- -----------------------------------------
CREATE TABLE IF NOT EXISTS `chw_info` (
  `chw_id` int(11) NOT NULL AUTO_INCREMENT,
  `chw_client_id` int(11) DEFAULT NULL,
  `chw_name` varchar(100) DEFAULT NULL,
  `chw_center_id` int(11) DEFAULT NULL,
  `chw_village` varchar(100) DEFAULT NULL,
  `chw_location` varchar(100) DEFAULT NULL,
  `chw_entry_date` date DEFAULT NULL,
  `chw_adm_no` varchar(30) DEFAULT NULL,
  `chw_sex` tinyint(1) DEFAULT NULL,
  `chw_old` tinyint(1) DEFAULT NULL,
  `chw_age` varchar(5) DEFAULT NULL,
  `chw_hasplan` tinyint(1) DEFAULT NULL,
  `chw_arv` tinyint(1) DEFAULT NULL,
  `chw_arv_note` tinyint(1) DEFAULT NULL,
  `chw_oir` tinyint(1) DEFAULT NULL,
  `chw_oir_note` varchar(100) DEFAULT NULL,
  `chw_tb` tinyint(1) DEFAULT NULL,
  `chw_nutrition` text,
  `chw_adh_support` int(11) DEFAULT NULL,
  `chw_assess` varchar(50) DEFAULT NULL,
  `chw_support` varchar(50) DEFAULT NULL,
  `chw_comm_mob` varchar(50) DEFAULT NULL,
  `chw_refers` text,
  `chw_remarks` text,
  PRIMARY KEY (`chw_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;
-- --------------------------------
alter table clients
add `client_gender` enum('1','2') DEFAULT NULL,
add  `client_dob` date DEFAULT NULL,
add  `client_doa` date DEFAULT NULL,
add  `client_center` int(3) DEFAULT NULL,
ADD INDEX `update_index` ( `client_adm_no` , `client_first_name` , `client_other_name` , `client_last_name` );
-- -----------------------------------------
alter table clients_staging
add `client_gender` enum('1','2') DEFAULT NULL,
add  `client_dob` date DEFAULT NULL,
add  `client_doa` date DEFAULT NULL;
-- ---------------------------------------
CREATE TABLE IF NOT EXISTS `client_status_history` (
  `status_history_client_id` int(10) NOT NULL,
  `status_history_status_date` datetime NOT NULL,
  `status_history_old_status` int(10) NOT NULL,
  `status_history_new_status` int(10) NOT NULL,
  PRIMARY KEY (`status_history_client_id`,`status_history_status_date`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
-- -----------------------------------------
CREATE TABLE IF NOT EXISTS `client_status_history_staging` (
  `client_adm_no` varchar(150) DEFAULT NULL,
  `client_first_name` varchar(150) DEFAULT NULL,
  `client_other_name` varchar(150) DEFAULT NULL,
  `client_last_name` varchar(150) DEFAULT NULL,
  `client_id` int(10) DEFAULT NULL,
  `status_history_client_id` int(10) DEFAULT NULL,
  `status_history_status_date` datetime DEFAULT NULL,
  `status_history_old_status` int(10) DEFAULT NULL,
  `status_history_new_status` int(10) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
-- -------------------------------------------
ALTER TABLE `clinical_visits` CHANGE `clinical_referral` `clinical_referral_old` INT( 11 ) NULL DEFAULT NULL ;
-- -------------------------------------------
alter table clinical_visits 
add  `clinical_complaints` tinyint(2) DEFAULT NULL,
add  `clinical_ctscan` varchar(200) NOT NULL,
add  `clinical_astal` varchar(200) NOT NULL,
add  `clinical_mouth_thrush` tinyint(1) DEFAULT NULL,
add  `clinical_mouth_ulcer` tinyint(1) DEFAULT NULL,
add  `clinical_teeth_opt` tinyint(1) DEFAULT NULL,
add  `clinical_ears_opt` tinyint(1) DEFAULT NULL,
add `clinical_throat` tinyint(1) DEFAULT NULL,
add `clinical_chest_creps` tinyint(1) DEFAULT NULL,
add `clinical_skin_opts` tinyint(1) DEFAULT NULL,
add   `clinical_cns` tinyint(4) DEFAULT NULL,
add  `clinical_eyes` tinyint(1) DEFAULT NULL,
add  `clinical_eyes_opt` varchar(200) DEFAULT NULL,
add  `clinical_muscle` tinyint(4) DEFAULT NULL,
drop `clinical_child_condition`,
add `clinical_tb_treat` tinyint(1) DEFAULT NULL,
add `clinical_dss` varchar(30) DEFAULT NULL,
drop `clinical_investigations_blood`,
drop `clinical_investigations_xray`,
add   `clinical_arv_on` tinyint(1) DEFAULT NULL,
add  `clinical_arv_on_adh` tinyint(1) DEFAULT NULL,
add   `clinical_tb_status` tinyint(1) DEFAULT NULL,
add  `clinical_tb_status_notes` varchar(200) DEFAULT NULL,
add `clinical_stage` tinyint(1) DEFAULT NULL,
add `clinical_referral` tinyint(2) DEFAULT NULL,
add  `clinical_referral_other` varchar(150) DEFAULT NULL,
add   `clinical_request` tinyint(1) DEFAULT NULL,
add  `clinical_request_list` varchar(50) DEFAULT NULL,
add  `clinical_other` varchar(200) DEFAULT NULL,
add  `clinical_therapy_stage` tinyint(2) DEFAULT NULL;
-- --------------------------------------------------
ALTER TABLE clinical_visits_staging DROP clinical_referral;
-- -------------------------------------------------
alter table clinical_visits_staging
-- add  `clinical_arv_drugs_other` varchar(150) DEFAULT NULL,
add  `clinical_complaints` tinyint(2) DEFAULT NULL,
add  `clinical_ctscan` varchar(200) NOT NULL,
add  `clinical_astal` varchar(200) NOT NULL,
add  `clinical_mouth_thrush` tinyint(1) DEFAULT NULL,
add  `clinical_mouth_ulcer` tinyint(1) DEFAULT NULL,
add  `clinical_teeth_opt` tinyint(1) DEFAULT NULL,
add  `clinical_ears_opt` tinyint(1) DEFAULT NULL,
add  `clinical_throat` tinyint(1) DEFAULT NULL,
add  `clinical_chest_creps` tinyint(1) DEFAULT NULL,
add  `clinical_skin_opts` tinyint(1) DEFAULT NULL,
add  `clinical_cns` tinyint(4) DEFAULT NULL,
add  `clinical_eyes` tinyint(1) DEFAULT NULL,
add  `clinical_eyes_opt` varchar(200) DEFAULT NULL,
add  `clinical_muscle` tinyint(4) DEFAULT NULL,
drop `clinical_child_condition`,
add  `clinical_tb_treat` tinyint(1) DEFAULT NULL,
add  `clinical_dss` varchar(30) DEFAULT NULL,
drop `clinical_investigations_blood`,
drop `clinical_investigations_xray`,
add  `clinical_arv_on` tinyint(1) DEFAULT NULL,
add  `clinical_arv_on_adh` tinyint(1) DEFAULT NULL,
add  `clinical_tb_status` tinyint(1) DEFAULT NULL,
add  `clinical_tb_status_notes` varchar(200) DEFAULT NULL,
add  `clinical_stage` tinyint(1) DEFAULT NULL,
add  `clinical_referral` tinyint(2) DEFAULT NULL,
add  `clinical_referral_old` INT( 11 ) NULL DEFAULT NULL ,
add  `clinical_referral_other` varchar(150) DEFAULT NULL,
add  `clinical_request` tinyint(1) DEFAULT NULL,
add  `clinical_request_list` varchar(50) DEFAULT NULL,
add  `clinical_other` varchar(200) DEFAULT NULL,
add  `clinical_therapy_stage` tinyint(2) DEFAULT NULL,
--	add  `clinical_arv_drugs_other` varchar(150) DEFAULT NULL,
ADD INDEX  `clinical_staff_name` (  `clinical_id` ,  `clinical_staff_name` ),
ADD INDEX  `clinical_referral_name` (  `clinical_id` ,  `clinical_referral_name` );
-- --------------------------------------------------------------
alter table counselling_info
add   `counselling_vct_camp` tinyint(1) unsigned DEFAULT NULL,
add  `counselling_vct_camp_site` varchar(100) DEFAULT NULL,
add  `counselling_return` tinyint(1) unsigned DEFAULT NULL,
add  `counselling_client_code` varchar(100) DEFAULT NULL,
add  `counselling_partner_code` varchar(100) DEFAULT NULL,
add  `counselling_area` varchar(100) DEFAULT NULL,
add  `counselling_gender` tinyint(1) unsigned DEFAULT NULL,
add  `counselling_marital` tinyint(1) unsigned DEFAULT NULL,
add  `counselling_client_seen` tinyint(1) unsigned DEFAULT NULL,
add  `counselling_final` tinyint(1) unsigned DEFAULT NULL,
add  `counselling_dis_couple` tinyint(1) unsigned DEFAULT NULL,
add  `counselling_mother_treatment_where` varchar(100) DEFAULT NULL,
add  `counselling_mother_pmtct_where` varchar(100) DEFAULT NULL,
add  `counselling_mother_antenatal_where` varchar(100) DEFAULT NULL,
add  `counselling_mother_cd4_note` varchar(50) DEFAULT NULL,
add  `counselling_positive_ref` tinyint(4) DEFAULT NULL,
add  `counselling_positive_ref_notes` varchar(100) DEFAULT NULL,
add  `counselling_admission_date` date DEFAULT NULL;
-- -------------------------------------------
alter table counselling_staging
add   `counselling_vct_camp` tinyint(1) unsigned DEFAULT NULL,
add  `counselling_vct_camp_site` varchar(100) DEFAULT NULL,
add  `counselling_return` tinyint(1) unsigned DEFAULT NULL,
add  `counselling_client_code` varchar(100) DEFAULT NULL,
add  `counselling_partner_code` varchar(100) DEFAULT NULL,
add  `counselling_area` varchar(100) DEFAULT NULL,
add  `counselling_gender` tinyint(1) unsigned DEFAULT NULL,
add  `counselling_marital` tinyint(1) unsigned DEFAULT NULL,
add  `counselling_client_seen` tinyint(1) unsigned DEFAULT NULL,
add  `counselling_final` tinyint(1) unsigned DEFAULT NULL,
add  `counselling_dis_couple` tinyint(1) unsigned DEFAULT NULL,
add  `counselling_mother_treatment_where` varchar(100) DEFAULT NULL,
add  `counselling_mother_pmtct_where` varchar(100) DEFAULT NULL,
add  `counselling_mother_antenatal_where` varchar(100) DEFAULT NULL,
add  `counselling_mother_cd4_note` varchar(50) DEFAULT NULL,
add  `counselling_positive_ref` tinyint(4) DEFAULT NULL,
add  `counselling_positive_ref_notes` varchar(100) DEFAULT NULL,
add  `counselling_other_notes` varchar(50) NULL DEFAULT NULL AFTER `counselling_custom`,
add  `counselling_admission_date` date DEFAULT NULL,
ADD INDEX  `counselling_name` (  `counselling_id` ,  `counselling_staff_name` );
-- --------------------------------------
alter table counselling_visit
change `counselling_child_knows_status` `counselling_child_knows_status_old` int(10) DEFAULT NULL;
-- -------------------------------------------
alter table counselling_visit
add `counselling_child_knows_status` tinyint(2) DEFAULT NULL,
add  `counselling_second_ident` tinyint(1) DEFAULT NULL,
add  `counselling_referer` tinyint(1) DEFAULT NULL,
add  `counselling_referer_other` varchar(150) DEFAULT NULL,
add  `counselling_next_visit` date DEFAULT NULL;
-- --------------------------------------------------
alter table counselling_visit_staging
add  `counselling_second_ident` tinyint(1) DEFAULT NULL,
add  `counselling_referer` tinyint(1) DEFAULT NULL,
add  `counselling_referer_other` varchar(150) DEFAULT NULL,
add  `counselling_next_visit` date DEFAULT NULL,
CHANGE  `counselling_child_knows_status`  `counselling_child_knows_status_old` INT( 10 ) NULL DEFAULT NULL,
ADD  `counselling_child_knows_status` TINYINT( 2 ) UNSIGNED NULL DEFAULT NULL;
-- ----------------------------------------------
CREATE TABLE IF NOT EXISTS `followup_info` (
  `followup_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `followup_client_id` int(11) DEFAULT NULL,
  `followup_adm_no` varchar(20) NOT NULL,
  `followup_client_type` tinyint(1) DEFAULT NULL,
  `followup_object` varchar(100) DEFAULT NULL,
  `followup_visit_type` tinyint(1) DEFAULT NULL,
  `followup_issues` varchar(150) DEFAULT NULL,
  `followup_issues_notes` varchar(150) DEFAULT NULL,
  `followup_service` varchar(50) DEFAULT NULL,
  `followup_service_notes` varchar(150) DEFAULT NULL,
  `followup_date` date DEFAULT NULL,
  `followup_center_id` int(11) DEFAULT NULL,
  `followup_officer_id` int(11) DEFAULT NULL,
  `followup_visit_mode` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`followup_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 ;
-- --------------------------------------------------
INSERT INTO `gacl_acl` (`id`, `section_value`, `allow`, `enabled`, `return_value`, `note`, `updated_date`) VALUES ('50', 'user', '1', '1', '', '', unix_timestamp(now()));
-- --------------------------------------------------
 INSERT INTO `gacl_axo_map` (`acl_id`, `section_value`, `value`) VALUES ('50', 'app', 'outputs');
-- --------------------------------------------
 INSERT INTO `gacl_aco_map` (`acl_id`, `section_value`, `value`) VALUES('50', 'application', 'access'),
(50, 'application', 'add'),
(50, 'application', 'delete'),
(50, 'application', 'edit'),
(50, 'application', 'view');
-- --------------------------------------------------
 INSERT INTO `gacl_aro_map` (`acl_id`, `section_value`, `value`) VALUES ('50', 'user', '1');

-- -- ----------------------------------------------------
ALTER TABLE `medical_assessment` CHANGE `medical_referral` `medical_referral_old` INT( 11 ) NULL DEFAULT NULL ;
-- ----------------------------------------------------
alter table medical_assessment 
add `medical_salvage` varchar(150) DEFAULT NULL,
add `medical_salvage_startdate` date DEFAULT NULL,
add `medical_salvage_enddate` date DEFAULT NULL,
add `medical_gait_opt` tinyint(1) DEFAULT NULL,
add `medical_handuse_opt` tinyint(1) DEFAULT NULL,
add `medical_referral` tinyint(2) DEFAULT NULL,
add  `medical_heart_rate` tinyint(5) DEFAULT NULL,
add  `medical_resp_rate` tinyint(5) DEFAULT NULL,
add  `medical_skin_type` tinyint(1) DEFAULT NULL,
add  `medical_skin_note` varchar(200) DEFAULT NULL,
add  `medical_chest_shape` tinyint(1) DEFAULT NULL,
add  `medical_cns` tinyint(1) unsigned DEFAULT NULL,
add  `medical_cns_note` varchar(200) DEFAULT NULL,
add  `medical_muscle` tinyint(1) unsigned DEFAULT NULL,
add  `medical_muscle_note` varchar(200) DEFAULT NULL,
add  `medical_request` tinyint(1) DEFAULT NULL,
add  `medical_request_opts` varchar(50) DEFAULT NULL,
add  `medical_request_note` varchar(200) DEFAULT NULL,
add  `medical_next_visit` date DEFAULT NULL;
-- ----------------------------------------------------
alter table medical_staging
add `medical_salvage` varchar(150) DEFAULT NULL,
add `medical_salvage_startdate` date DEFAULT NULL,
add `medical_salvage_enddate` date DEFAULT NULL,
add `medical_gait_opt` tinyint(1) DEFAULT NULL,
add `medical_handuse_opt` tinyint(1) DEFAULT NULL,
add  `medical_heart_rate` tinyint(5) DEFAULT NULL,
add  `medical_resp_rate` tinyint(5) DEFAULT NULL,
add  `medical_skin_type` tinyint(1) DEFAULT NULL,
add  `medical_skin_note` varchar(200) DEFAULT NULL,
add  `medical_chest_shape` tinyint(1) DEFAULT NULL,
add  `medical_cns` tinyint(1) unsigned DEFAULT NULL,
add  `medical_cns_note` varchar(200) DEFAULT NULL,
add  `medical_muscle` tinyint(1) unsigned DEFAULT NULL,
add  `medical_muscle_note` varchar(200) DEFAULT NULL,
add  `medical_request` tinyint(1) DEFAULT NULL,
add  `medical_request_opts` varchar(50) DEFAULT NULL,
add  `medical_request_note` varchar(200) DEFAULT NULL,
add  `medical_next_visit` date DEFAULT NULL,
add  `medical_referral_old` INT( 11 ) NULL DEFAULT NULL;
-- ---------------------------------------------------------
INSERT INTO `modules` (`mod_id`, `mod_name`, `mod_directory`, `mod_version`, `mod_setup_class`, `mod_type`, `mod_active`, `mod_ui_name`, `mod_ui_icon`, `mod_ui_order`, `mod_ui_active`, `mod_description`, `permissions_item_table`, `permissions_item_field`, `permissions_item_label`) VALUES
(33, 'Outputs', 'outputs', '0.1', 'CSetupOutputs', 'core', 1, 'Outputs', '', 26, 1, 'A module for parsing and analyzing existing data', NULL, NULL, NULL);
-- ----------------------------------------------------
alter table `mortality_staging` 
add `mortality_clinical_course` varchar(150) DEFAULT NULL,
add  `mortality_postmortem_where` varchar(150) DEFAULT NULL,
add  `mortality_recents_a` varchar(100) DEFAULT NULL,
add  `mortality_recents_b` varchar(100) DEFAULT NULL,
add  `mortality_malnutrition` tinyint(1) DEFAULT NULL,
add  `mortality_malnutrition_notes` tinyint(2) DEFAULT NULL,
add  `mortality_cd4` varchar(20) DEFAULT NULL,
add  `mortality_cd4_percentage` varchar(10) DEFAULT NULL,
add  `mortality_viral_load` varchar(20) DEFAULT NULL,
add  `mortality_hb` varchar(10) DEFAULT NULL,
add  `mortality_clinical_date` date DEFAULT NULL,
add  `mortality_arv` tinyint(1) DEFAULT NULL,
add  `mortality_arv_dateon` date DEFAULT NULL,
add  `mortality_arv_period` varchar(20) DEFAULT NULL,
add  `mortality_tb` tinyint(1) DEFAULT NULL,
add  `mortality_tb_start` date DEFAULT NULL,
add  `mortality_weight` varchar(10) DEFAULT NULL,
add  `mortality_height` varchar(10) DEFAULT NULL,
add  `mortality_nutrition_date` date DEFAULT NULL,
add  `mortality_enroll_date` date DEFAULT NULL,
add  `mortality_staff_name` varchar(200) NULL DEFAULT NULL,
ADD `mortality_clinical_officer_name` VARCHAR( 200 ) NULL DEFAULT NULL AFTER `mortality_cause_desc`,
add  `mortality_enrolled_time` varchar(20) DEFAULT NULL,
ADD INDEX  `mortality_staff_name` (  `mortality_id` ,  `mortality_staff_name` );
-- ------------------------------------------
alter table `mortality_info` 
add `mortality_clinical_course` varchar(150) DEFAULT NULL,
add  `mortality_postmortem_where` varchar(150) DEFAULT NULL,
add  `mortality_recents_a` varchar(100) DEFAULT NULL,
add  `mortality_recents_b` varchar(100) DEFAULT NULL,
add  `mortality_malnutrition` tinyint(1) DEFAULT NULL,
add  `mortality_malnutrition_notes` tinyint(2) DEFAULT NULL,
add  `mortality_cd4` varchar(20) DEFAULT NULL,
add  `mortality_cd4_percentage` varchar(10) DEFAULT NULL,
add  `mortality_viral_load` varchar(20) DEFAULT NULL,
add  `mortality_hb` varchar(10) DEFAULT NULL,
add  `mortality_clinical_date` date DEFAULT NULL,
add  `mortality_arv` tinyint(1) DEFAULT NULL,
add  `mortality_arv_dateon` date DEFAULT NULL,
add  `mortality_arv_period` varchar(20) DEFAULT NULL,
add  `mortality_tb` tinyint(1) DEFAULT NULL,
add  `mortality_tb_start` date DEFAULT NULL,
add  `mortality_weight` varchar(10) DEFAULT NULL,
add  `mortality_height` varchar(10) DEFAULT NULL,
add  `mortality_nutrition_date` date DEFAULT NULL,
add  `mortality_enroll_date` date DEFAULT NULL,
add  `mortality_enrolled_time` varchar(20) DEFAULT NULL;

-- ------------------------------------
CREATE TABLE IF NOT EXISTS `nutrition_service` (
  `nutrition_service_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `nutrition_service_client_id` int(11) DEFAULT NULL,
  `nutrition_service_visit_id` int(11) unsigned NOT NULL,
  `nutrition_service_program` varchar(200) DEFAULT NULL,
  `nutrition_service_item` varchar(200) DEFAULT NULL,
  `nutrition_service_qty` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`nutrition_service_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;
-- ------------------------------------------------
alter table nutrition_visit
add `nutrition_water` varchar(50) DEFAULT NULL,
add `nutrition_oedema` tinyint(1) DEFAULT NULL,
add  `nutrition_beverages_title` varchar(100) DEFAULT NULL,
add  `nutrition_beverages_notes` varchar(50) DEFAULT NULL,
add  `nutrition_ugali` varchar(50) DEFAULT NULL,
add  `nutrition_rice` varchar(50) DEFAULT NULL,
add  `nutrition_banan` varchar(50) DEFAULT NULL,
add  `nutrition_tubers` varchar(50) DEFAULT NULL,
add  `nutrition_wheat` varchar(50) DEFAULT NULL,
add  `nutrition_carbos_title` varchar(50) DEFAULT NULL,
add  `nutrition_carbos_notes` varchar(50) DEFAULT NULL,
add  `nutrition_protein_title` varchar(50) DEFAULT NULL,
add  `nutrition_protein_notes` varchar(50) DEFAULT NULL,
add  `nutrition_fat` varchar(50) DEFAULT NULL,
add  `nutrition_issue_notes` varchar(100) DEFAULT NULL,
add  `nutrition_program` varchar(20) DEFAULT NULL,
add  `nutrition_program_other` varchar(50) DEFAULT NULL,
add  `nutrition_rendered` varchar(20) DEFAULT NULL,
add  `nutrition_next_visit` date DEFAULT NULL,
add  `nutrition_refer` tinyint(2) DEFAULT NULL,
add  `nutrition_refer_other` varchar(100) DEFAULT NULL,
add  `nutrition_service_other` varchar(50) DEFAULT NULL;
-- -----------------------------
alter table nutrition_staging
add `nutrition_water` varchar(50) DEFAULT NULL,
add `nutrition_oedema` tinyint(1) DEFAULT NULL,
add  `nutrition_beverages_title` varchar(100) DEFAULT NULL,
add  `nutrition_beverages_notes` varchar(50) DEFAULT NULL,
add  `nutrition_ugali` varchar(50) DEFAULT NULL,
add  `nutrition_rice` varchar(50) DEFAULT NULL,
add  `nutrition_banan` varchar(50) DEFAULT NULL,
add  `nutrition_tubers` varchar(50) DEFAULT NULL,
add  `nutrition_wheat` varchar(50) DEFAULT NULL,
add  `nutrition_carbos_title` varchar(50) DEFAULT NULL,
add  `nutrition_carbos_notes` varchar(50) DEFAULT NULL,
add  `nutrition_protein_title` varchar(50) DEFAULT NULL,
add  `nutrition_protein_notes` varchar(50) DEFAULT NULL,
add  `nutrition_fat` varchar(50) DEFAULT NULL,
add  `nutrition_issue_notes` varchar(100) DEFAULT NULL,
add  `nutrition_program` varchar(20) DEFAULT NULL,
add  `nutrition_program_other` varchar(50) DEFAULT NULL,
add  `nutrition_rendered` varchar(20) DEFAULT NULL,
add  `nutrition_next_visit` date DEFAULT NULL,
add  `nutrition_refer` tinyint(2) DEFAULT NULL,
add  `nutrition_refer_other` varchar(100) DEFAULT NULL,
add  `nutrition_service_other` varchar(50) DEFAULT NULL,
ADD INDEX  `nutrition_staff_name` (  `nutrition_id` ,  `nutrition_staff_name` );
-- ----------------------------------------
alter table social_services
add `social_services_value` varchar(50) DEFAULT NULL;
-- -------------------------------------------------
alter table social_services_staging
add `social_services_value` varchar(50) DEFAULT NULL;
-- -------------------------------------------------

CREATE TABLE IF NOT EXISTS `social_visit_slim` (
  `social_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `social_client_id` int(10) unsigned NOT NULL,
  `social_staff_id` int(10) unsigned DEFAULT NULL,
  `social_clinic_id` int(10) unsigned DEFAULT NULL,
  `social_entry_date` date DEFAULT NULL,
  `social_client_status` int(10) unsigned DEFAULT NULL,
  `social_client_health` tinyint(1) unsigned DEFAULT NULL,
  `social_visit_type` int(10) unsigned DEFAULT NULL,
  `social_death` int(10) DEFAULT NULL,
  `social_death_notes` varchar(100) DEFAULT '',
  `social_death_date` date DEFAULT NULL,
  `social_caregiver_pri_change` tinyint(2) DEFAULT NULL,
  `social_caregiver_pri_change_notes` varchar(100) DEFAULT NULL,
  `social_caregiver_sec_change` tinyint(2) unsigned DEFAULT NULL,
  `social_caregiver_sec_change_notes` varchar(100) DEFAULT NULL,
  `social_caregiver_relationship` varchar(100) DEFAULT '',
  `social_caregiver_pri_health_child_impact` tinyint(2) unsigned DEFAULT NULL,
  `social_caregiver_sec_health_child_impact` tinyint(2) unsigned DEFAULT NULL,
  `social_caregiver_pri_health` tinyint(1) unsigned DEFAULT NULL,
  `social_caregiver_sec_health` tinyint(1) unsigned DEFAULT NULL,
  `social_residence_mobile` varchar(100) DEFAULT NULL,
  `social_residence` varchar(255) DEFAULT NULL,
  `social_caregiver_pri_employment_change` tinyint(2) DEFAULT NULL,
  `social_caregiver_pri_new_employment` tinyint(2) DEFAULT NULL,
  `social_caregiver_pri_new_employment_desc` varchar(100) DEFAULT NULL,
  `social_caregiver_sec_employment_change` tinyint(2) DEFAULT NULL,
  `social_caregiver_sec_new_employment` tinyint(2) DEFAULT NULL,
  `social_caregiver_sec_new_employment_desc` varchar(100) DEFAULT NULL,
  `social_caregiver_pri_new_income` tinyint(2) DEFAULT NULL,
  `social_school_attendance` int(10) DEFAULT NULL,
  `social_school` int(10) DEFAULT NULL,
  `social_reason_not_attending` int(10) DEFAULT NULL,
  `social_reason_not_attending_notes` varchar(150) DEFAULT NULL,
  `social_relocation` varchar(150) DEFAULT NULL,
  `social_iga` varchar(150) DEFAULT NULL,
  `social_placement` varchar(150) DEFAULT NULL,
  `social_succession_planning` varchar(150) DEFAULT NULL,
  `social_legal` varchar(150) DEFAULT NULL,
  `social_nursing` varchar(150) DEFAULT NULL,
  `social_transport` varchar(150) DEFAULT NULL,
  `social_education` varchar(150) DEFAULT NULL,
  `social_food` varchar(150) DEFAULT NULL,
  `social_rent` varchar(150) DEFAULT NULL,
  `social_solidarity` varchar(150) DEFAULT NULL,
  `social_direct_support` varchar(150) DEFAULT NULL,
  `social_medical_support` varchar(150) DEFAULT NULL,
  `social_medical_support_desc` varchar(100) DEFAULT '',
  `social_other_support` varchar(150) DEFAULT NULL,
  `social_othersupport_value` double DEFAULT NULL,
  `social_permanency_value` double DEFAULT NULL,
  `social_succession_value` double DEFAULT NULL,
  `social_legal_value` double DEFAULT NULL,
  `social_nursing_value` double DEFAULT NULL,
  `social_transport_value` double DEFAULT NULL,
  `social_education_value` double DEFAULT NULL,
  `social_food_value` double DEFAULT NULL,
  `social_rent_value` double DEFAULT NULL,
  `social_solidarity_value` double DEFAULT NULL,
  `social_directsupport_value` double DEFAULT NULL,
  `social_medicalsupport_value` double DEFAULT NULL,
  `social_risk_level` int(10) DEFAULT NULL,
  `social_notes` text,
  `social_custom` longtext,
  `social_change` int(11) unsigned DEFAULT NULL,
  `social_training` tinyint(1) unsigned DEFAULT NULL,
  `social_training_desc` varchar(150) DEFAULT NULL,
  `social_next_visit` date DEFAULT NULL,
  `social_referral` tinyint(2) unsigned DEFAULT NULL,
  `social_caregiver_pri` int(11) unsigned DEFAULT NULL,
  `social_caregiver_sec` int(11) unsigned DEFAULT NULL,
  `social_caregiver_pri_type` tinyint(1) DEFAULT NULL,
  `social_caregiver_sec_type` tinyint(1) DEFAULT NULL,
  `social_nhf` tinyint(1) DEFAULT NULL,
  `social_nhf_y` varchar(100) DEFAULT NULL,
  `social_nhf_n` varchar(100) DEFAULT NULL,
  `social_immun` tinyint(1) DEFAULT NULL,
  `social_immun_y` varchar(100) DEFAULT NULL,
  `social_immun_n` varchar(100) DEFAULT NULL,
  `social_caregiver_employment_change` tinyint(2) DEFAULT NULL,
  `social_caregiver_new_employment` tinyint(2) DEFAULT NULL,
  `social_caregiver_new_employment_desc` varchar(100) DEFAULT NULL,
  `social_class_form` varchar(150) DEFAULT NULL,
  `social_caregiver_income` tinyint(1) unsigned DEFAULT NULL,
  PRIMARY KEY (`social_id`),
  UNIQUE KEY `social_id` (`social_id`),
  KEY `social_client` (`social_id`,`social_client_id`),
  KEY `social_clinic` (`social_id`,`social_clinic_id`),
  KEY `client_staff_id` (`social_client_id`,`social_staff_id`),
  KEY `client_clinic` (`social_client_id`,`social_clinic_id`),
  KEY `staff_clinic` (`social_staff_id`,`social_clinic_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1;
-- -------------------------------------------------
drop table if exists social_staging;
-- ------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_staging` (
  `social_id` int(10) DEFAULT NULL,
  `new_social_id` int(11) DEFAULT NULL,
  `social_client_id` int(10) DEFAULT NULL,
  `client_adm_no` varchar(50) DEFAULT NULL,
  `client_first_name` varchar(100) DEFAULT '',
  `client_other_name` varchar(100) DEFAULT '',
  `client_last_name` varchar(100) DEFAULT '',
  `social_staff_id` int(10) DEFAULT NULL,
  `social_staff_name` varchar(150) DEFAULT NULL,
  `contact_first_name` varchar(30) DEFAULT NULL,
  `contact_other_name` varchar(255) DEFAULT NULL,
  `contact_last_name` varchar(30) DEFAULT NULL,
  `social_clinic_id` int(10) DEFAULT NULL,
  `clinic_name` varchar(100) DEFAULT '',
  `social_entry_date` date DEFAULT NULL,
  `social_client_status` int(10) DEFAULT NULL,
  `social_visit_type` int(10) DEFAULT NULL,
  `social_death` int(10) DEFAULT NULL,
  `social_death_notes` varchar(100) DEFAULT '',
  `social_death_date` date DEFAULT NULL,
  `social_caregiver_pri_change` tinyint(2) DEFAULT NULL,
  `social_caregiver_pri_change_notes` varchar(100) DEFAULT NULL,
  `social_caregiver_sec_change` tinyint(2) unsigned DEFAULT NULL,
  `social_caregiver_sec_change_notes` varchar(100) DEFAULT NULL,
  `social_caregiver_relationship` varchar(100) DEFAULT '',
  `social_caregiver_pri_health_child_impact` tinyint(2) unsigned DEFAULT NULL,
  `social_caregiver_sec_health_child_impact` tinyint(2) unsigned DEFAULT NULL,
  `social_caregiver_pri_health` tinyint(1) unsigned DEFAULT NULL,
  `social_caregiver_sec_health` tinyint(1) unsigned DEFAULT NULL,
  `social_caregiver_change` int(10) DEFAULT NULL,
  `social_caregiver_change_notes` varchar(100) DEFAULT '',
  `social_caregiver_fname` varchar(100) DEFAULT '',
  `social_caregiver_lname` varchar(100) DEFAULT '',
  `social_caregiver_age` double DEFAULT NULL,
  `social_caregiver_status` int(10) DEFAULT NULL,
  `social_caregiver_education` int(10) DEFAULT NULL,
  `social_caregiver_employment` int(10) DEFAULT NULL,
  `social_caregiver_idno` varchar(100) DEFAULT '',
  `social_caregiver_mobile` varchar(100) DEFAULT '',
  `social_caregiver_health` int(10) DEFAULT NULL,
  `social_caregiver_health_child_impact` int(10) DEFAULT NULL,
  `social_residence_mobile` varchar(100) DEFAULT '',
  `social_residence` varchar(255) DEFAULT NULL,
  `social_caregiver_pri_employment_change` tinyint(2) DEFAULT NULL,
  `social_caregiver_pri_new_employment` tinyint(2) DEFAULT NULL,
  `social_caregiver_pri_new_employment_desc` varchar(100) DEFAULT NULL,
  `social_caregiver_sec_employment_change` tinyint(2) DEFAULT NULL,
  `social_caregiver_sec_new_employment` tinyint(2) DEFAULT NULL,
  `social_caregiver_sec_new_employment_desc` varchar(100) DEFAULT NULL,
  `social_caregiver_pri_new_income` tinyint(2) DEFAULT NULL,
  `social_caregiver_new_income` int(10) DEFAULT NULL,
  `social_school_attendance` int(10) DEFAULT NULL,
  `social_school` int(10) DEFAULT NULL,
  `social_reason_not_attending` int(10) DEFAULT NULL,
  `social_relocation` varchar(150) DEFAULT NULL,
  `social_iga` varchar(150) DEFAULT NULL,
  `social_placement` varchar(150) DEFAULT NULL,
  `social_succession_planning` varchar(150) DEFAULT NULL,
  `social_legal` varchar(150) DEFAULT NULL,
  `social_nursing` varchar(150) DEFAULT NULL,
  `social_transport` varchar(150) DEFAULT NULL,
  `social_education` varchar(150) DEFAULT NULL,
  `social_food` varchar(150) DEFAULT NULL,
  `social_rent` varchar(150) DEFAULT NULL,
  `social_solidarity` varchar(150) DEFAULT NULL,
  `social_direct_support` varchar(150) DEFAULT NULL,
  `social_medical_support` varchar(150) DEFAULT NULL,
  `social_medical_support_desc` varchar(100) DEFAULT '',
  `social_other_support` varchar(150) DEFAULT NULL,
  `social_othersupport_value` double DEFAULT NULL,
  `social_permanency_value` double DEFAULT NULL,
  `social_succession_value` double DEFAULT NULL,
  `social_legal_value` double DEFAULT NULL,
  `social_nursing_value` double DEFAULT NULL,
  `social_transport_value` double DEFAULT NULL,
  `social_education_value` double DEFAULT NULL,
  `social_food_value` double DEFAULT NULL,
  `social_rent_value` double DEFAULT NULL,
  `social_solidarity_value` double DEFAULT NULL,
  `social_directsupport_value` double DEFAULT NULL,
  `social_medicalsupport_value` double DEFAULT NULL,
  `social_risk_level` int(10) DEFAULT NULL,
  `social_notes` text,
  `social_custom` longtext,
  `social_change` int(11) unsigned DEFAULT NULL,
  `social_training` tinyint(1) unsigned DEFAULT NULL,
  `social_training_desc` varchar(150) DEFAULT NULL,
  `social_next_visit` date DEFAULT NULL,
  `social_referral` tinyint(2) unsigned DEFAULT NULL,
  `social_caregiver_pri` int(11) unsigned DEFAULT NULL,
  `social_caregiver_sec` int(11) unsigned DEFAULT NULL,
  `social_caregiver_pri_type` tinyint(1) DEFAULT NULL,
  `social_caregiver_sec_type` tinyint(1) DEFAULT NULL,
  `social_nhf` tinyint(1) DEFAULT NULL,
  `social_nhf_y` varchar(100) DEFAULT NULL,
  `social_nhf_n` varchar(100) DEFAULT NULL,
  `social_immun` tinyint(1) DEFAULT NULL,
  `social_immun_y` varchar(100) DEFAULT NULL,
  `social_immun_n` varchar(100) DEFAULT NULL,
  `social_caregiver_employment_change` tinyint(2) DEFAULT NULL,
  `social_caregiver_new_employment` tinyint(2) DEFAULT NULL,
  `social_caregiver_new_employment_desc` varchar(100) DEFAULT NULL,
  `social_class_form` varchar(150) DEFAULT NULL,
  `social_caregiver_income` tinyint(1) unsigned DEFAULT NULL,
  `social_client_health` TINYINT( 1 ) UNSIGNED NULL DEFAULT NULL,
  `social_reason_not_attending_notes` VARCHAR( 150 ) NULL DEFAULT NULL,
  INDEX  `social_staff_name` (  `social_id` ,  `social_staff_name` ),
  KEY `social_client` (`social_id`,`social_client_id`),
  KEY `social_adm_no` (`social_id`,`client_adm_no`),
  KEY `social_staff` (`social_id`,`social_staff_id`),
  KEY `social_clinic` (`social_id`,`social_clinic_id`),
  KEY `social_client_adm_no` (`social_client_id`,`client_adm_no`),
  KEY `client_staff_id` (`social_client_id`,`social_staff_id`),
  KEY `client_clinic` (`social_client_id`,`social_clinic_id`),
  KEY `adm_no_staff_id` (`client_adm_no`,`social_staff_id`),
  KEY `adm_no_clinic` (`client_adm_no`,`social_clinic_id`),
  KEY `staff_id_clinic` (`social_staff_id`,`social_clinic_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
-- --------------------------------------------------
alter table training_staging
  ADD `training_custom` longtext default null,
  ADD `training_curriculum` int( 11 ) DEFAULT NULL ,ADD `training_curriculum_desc` varchar( 150 ) DEFAULT NULL;
-- --------------------------------------------------
 truncate `sysvals` ;

INSERT INTO `sysvals` (`sysval_id`, `sysval_key_id`, `sysval_title`, `sysval_value`) VALUES
(1, 1, 'ProjectStatus', '0|Not Defined\r\n1|Proposed\r\n2|In Planning\r\n3|In Progress\r\n4|On Hold\r\n5|Complete\r\n6|Template'),
(2, 1, 'CompanyType', '0|Not Applicable\r\n1|Members\r\n2|Donors\r\n3|Partners\r\n4|Vendors\r\n5|Suppliers\r\n6|Consultant\r\n7|Government\r\n8|Internal'),
(3, 1, 'TaskDurationType', '1|hours\n24|days'),
(4, 1, 'EventType', '0|General\n1|Appointment\n2|Meeting\n3|All Day Event\n4|Anniversary\n5|Reminder'),
(5, 1, 'TaskStatus', '0|Active\n-1|Inactive'),
(6, 1, 'TaskType', '0|Unknown\n1|Administrative\n2|Operative'),
(7, 1, 'ProjectType', '0|Unknown\n1|Administrative\n2|Operative'),
(8, 3, 'ProjectColors', 'Web|FFE0AE\nEngineering|AEFFB2\nHelpDesk|FFFCAE\nSystem Administration|FFAEAE'),
(9, 1, 'FileType', '0|Unknown\n1|Document\n2|Application'),
(10, 1, 'TaskPriority', '-1|low\n0|normal\n1|high'),
(11, 1, 'ProjectPriority', '-1|low\n0|normal\n1|high'),
(12, 1, 'ProjectPriorityColor', '-1|#E5F7FF\n0|\n1|#FFDCB3'),
(13, 1, 'TaskLogReference', '0|Not Defined\n1|Email\n2|Helpdesk\n3|Phone Call\n4|Fax'),
(14, 1, 'TaskLogReferenceImage', '0| 1|./images/obj/email.gif 2|./modules/helpdesk/images/helpdesk.png 3|./images/obj/phone.gif 4|./images/icons/stock_print-16.png'),
(15, 1, 'ClientStatus', '1|Active\r\n5|Retested Negative\r\n10|Relocated\r\n3|Transfer Out\r\n6|Exits over 18yrs\r\n4|Deceased\r\n2|Lost to follow-up\r\n7|Transfer to LTP Centre\r\n8|Declined\r\n9|VCT'),
(16, 1, 'ClientPriority', '1|Low\r\n2|Medium\r\n3|High'),
(17, 1, 'YesNoND', '1|Yes\r\n2|No\r\n3|ND'),
(18, 1, 'RiskLevel', '1|Low\r\n2|Medium\r\n3|High'),
(19, 1, 'RelationType', '18|Grandfather\r\n19|Grandmother\r\n11|Father\r\n10|Mother\r\n16|Aunt\r\n15|Uncle\r\n13|Sister\r\n14|Brother\r\n20|Cousin\r\n21|Niece'),
(20, 1, 'CaregiverType', '1|Primary\r\n17|Secondary'),
(21, 1, 'CaregiverStatus', '1|Alive\r\n2|Deceased\r\n3|Not known'),
(22, 1, 'CaregiverCondition', '1|Elderly\r\n2|Sickly'),
(23, 1, 'EmploymentType', '1|Salaried\r\n2|Self\r\n3|Casual Labor\r\n4|Unemployed\r\n5|N.A.'),
(24, 1, 'GenderType', '1|Male\r\n2|Female'),
(25, 1, 'EducationLevel', '1|Primary\r\n2|Secondary\r\n3|Tertiary\r\n4|Never attended'),
(26, 1, 'Province', '0|Nairobi\r\n1|North Eastern\r\n2|Central\r\n3|Eastern\r\n4|Western\r\n5|Nyanza\r\n6|Coast\r\n7|Rift Valley'),
(27, 1, 'CaregiverHealthIssues', '1|Depression\r\n2|Alcohol or drug abuse\r\n3|Self-harm / suicide attempts\r\n4|Unknown\r\n5|None'),
(28, 1, 'DisclosureStatus', '1|Yes\r\n2|Disclosure process underway\r\n3|No'),
(29, 1, 'DisclosureResponse', '1|Raised with caregiver\r\n2|Initiated process   \r\n3|Post disclosure'),
(30, 1, 'DisclosureProcessStatus', '1|Fully prepared to disclose\r\n2|Need counselling support to disclose\r\n3|Willing to disclose but non-conducive environment\r\n4|No intention to disclose'),
(31, 1, 'HIVTreatmentOptions', '1|Yes, ARTs\r\n2|Yes but no ARTs\r\n3|No\r\n4|Unknown'),
(32, 1, 'StigmatizationOptions', '1|Not a concern\r\n2|Minor concern\r\n3|Major concern\r\n4|Unknown'),
(33, 1, 'ServiceOptions', '1|Support Counselling\r\n2|Child Counselling    \r\n3|Adherence Counselling\r\n4|Disclosure Counselling \r\n5|Preventive Education\r\n'),
(35, 1, 'DiarrhoeaType', '0|None\r\n1|Acute less 14 Days\r\n2|Chronic gereater 14 Days'),
(36, 1, 'DehydrationType', '1|None\r\n2|Some\r\n3|Severe'),
(37, 1, 'TBPulmonaryType', '1|Pulmonary\r\n2|Extrapulmonary'),
(38, 1, 'MalnutritionType', '0|None\r\n1|Moderate\r\n2|Severe'),
(39, 1, 'EarType', '1|Right\r\n2|Left\r\n3|Both\r\n4|None'),
(40, 1, 'ARVType', '1|AZT\r\n2|d4T\r\n3|3TC\r\n4|NVP\r\n5|EFV\r\n6|ddl\r\n7|ABC\r\n8|Kaletra\r\n9|TDF'),
(41, 1, 'TBDrugsType', '1|Rifampicin\r\n2|isoniazid\r\n3|pyrizanamide\r\n4|streptomycin\r\n5|Ethabutol \r\n6|pyridoxine'),
(42, 1, 'NutritionType', '1|RUTF\r\n2|Insta\r\n3|WFP for family\r\n4|Nan'),
(43, 1, 'BirthType', '1|NVD\r\n2|CS\r\n3|ND'),
(44, 1, 'BirthPlaceType', '1|Institution\r\n2|Home\r\n3|ND'),
(45, 1, 'EducationProgressType', '1|Good\r\n2|Satisfactory\r\n3|Poor'),
(46, 1, 'MotorAbilityType', '1|Sitting\r\n2|Walking\r\n3|Other'),
(47, 1, 'LymphType', '1|Cervical\r\n2|Axilla\r\n3|Groins'),
(48, 1, 'ThroatType', '1|Normal\r\n2|Red'),
(49, 1, 'TeethType', '1|Normal\r\n2|Caries'),
(50, 1, 'PercussionType', '1|Normal\r\n2|Reduceed'),
(51, 1, 'BreathSoundsType', '1|Vesicular\r\n2|Bronchial'),
(52, 1, 'SoundsType', '1|Creps-rales\r\n2|rhonchi\r\n3|transmitted'),
(53, 1, 'NormalDisplacedType', '1|Normal\r\n2|Displaced'),
(54, 1, 'NormalIncreasedType', '1|Normal\r\n2|Increased'),
(55, 1, 'FemoralPulseType', '1|felt\r\n2|difficult to feel'),
(56, 1, 'HeartType', '1|Murmur heard\r\n2|not heard'),
(57, 1, 'ImmunizationStatus', '1|Up to Date \r\n2|Incomplete \r\n3|Not known'),
(58, 1, 'NormalIncReducedType', '1|Normal\r\n2|Increased\r\n3|Reduced'),
(59, 1, 'PalpableType', '1|Palpable\r\n2|Impalpable'),
(60, 1, 'VisitType', '1|Clinic\r\n2|Home\r\n3|Hospital\r\n4|School'),
(61, 1, 'ChildHealthIssues', '1|Physical Abuse\r\n2|Verbal/Emotional Abuse\r\n3|Sexual Abuse\r\n4|Sexual relationships\r\n5|Poor self-esteem\r\n6|Depression\r\n7|Self-harm/Suicide attempts\r\n8|Alcohol / Drug Abuse\r\n9|None\r\n'),
(62, 1, 'ExaminationType', '1|Oedema\r\n2|Wasting\r\n3|Pallor\r\n4|Jaundice\r\n5|Cyanosis\r\n6|Clubbing'),
(63, 1, 'ConditionType', '1|Well-Active-Alert\r\n2|Ill-Lethargic-In Pain'),
(64, 1, 'AgeType', '1|Exact\r\n2|Estimated'),
(65, 1, 'StatusAwareType', '1|Before Pregnancy\r\n2|During Pregnancy\r\n3|After Pregnancy'),
(66, 1, 'IncomeLevels', '1|<1500\r\n2|1500-3000\r\n3|3000-5000\r\n4|>5000'),
(67, 1, 'MaritalStatus', '1|Married\r\n2|Divorced\r\n3|Single'),
(68, 1, 'ReasonsNotAttendingSchool', '1|Child ill\r\n2|Caregiver ill\r\n3|Financial Reasons\r\n4|Child Too Young \r\n5|Other\r\n'),
(69, 1, 'SocialVisitTypes', '1|Home\r\n2|Hospital\r\n3|Clinic\r\n4|School'),
(70, 1, 'CaregiverChangeTypes', '1|Death\r\n2|Separation or Divorce\r\n3|Relocation\r\n4|Other\r\n5|Change Role'),
(71, 1, 'CaregiverHealthStatus', '1|Disabled\r\n2|Chronically Ill\r\n3|Elderly'),
(72, 1, 'CaregiverHealthChanges', '1|Well-Active \r\n2|Sickly \r\n3|Bed-ridden\r\n'),
(73, 1, 'RelocationType', '1|Voluntary Request\r\n2|Transfer Out\r\n3|Difficult Prevailing Situation'),
(74, 1, 'IGAOptions', '1|No source of income\r\n2|Willing to start an IGA'),
(75, 1, 'PlacementType', '1|Adoption \r\n2|No primary caregiver \r\n3|Primary caregiver unable \r\n4|Institutionalised \r\n5|Caregiver not always available \r\n6|Nutritional Rehabilitation'),
(76, 1, 'SuccessionPlanningTypes', '1|Primary caregiver sickly\r\n2|Primary caregiver not always available'),
(77, 1, 'LegalIssues', '1|Physical abuse\r\n2|Sexual assault\r\n3|Caregiver unwilling to care\r\n4|Potential disinheritance'),
(78, 1, 'NursingCareTypes', '1|Bedridden child\r\n2|Bedridden caregiver'),
(79, 1, 'TransportNeeds', '1|Relocating\r\n2|Transfer out\r\n3|Fare to-from center\r\n'),
(80, 1, 'EducationNeeds', '1|Not enrolled\r\n2|No school uniform, books, fees\r\n3|Sent away from school'),
(81, 1, 'FoodNeeds', '1|No or low income \r\n2|Many dependants \r\n3|Client on ART \r\n4|Chronically ill or bedridden caregiver \r\n5|Elderly Caregiver \r\n6|Child headed household'),
(82, 1, 'RentNeeds', '1|Eviction\r\n2|Bedridden caregiver\r\n3|Loss of income activity\r\n4|Displacement'),
(83, 1, 'SolidarityNeeds', '1|Death of client\r\n2|Death of caregiver'),
(84, 1, 'DirectSupportNeeds', '1|No clothing\r\n2|Utensils\r\n3|Bedding\r\n4|Mosquito nets\r\n5|Other'),
(85, 1, 'MedicalSupportNeeds', '1|Hospital Bill \r\n2|Other'),
(86, 1, 'ChildSchoolLevels', '1|Pre-school\r\n2|Primary\r\n3|Secondary\r\n4|Tertiary'),
(87, 1, 'ChildSchoolStatus', '1|attending regularly\r\n2|child dropped out\r\n3|completed'),
(88, 1, 'DeathTypes', '1|Mother\r\n2|Father\r\n3|Primary Caregiver\r\n4|Secondary Caregiver\r\n5|Other'),
(89, 1, 'YesNo', '1|Yes\r\n2|No'),
(90, 1, 'InsecurityScore', '1|Rarely (once or twice in the past four weeks) \r\n2|Sometimes (three to ten times in the past four weeks)\r\n3|Often (more than ten times in the past four weeks) '),
(91, 1, 'CaregiverRelation', '1|Mother\r\n2|Father\r\n3|Sibling\r\n4|Grandparent\r\n5|Other'),
(92, 1, 'TreatmentType', '1|Start\r\n2|Continue\r\n3|Change Dose\r\n4|Stop\r\n5|Change Drug'),
(93, 1, 'ClearTypes', '1|Clear \r\n2|Not Clear'),
(94, 1, 'GrowthType', '1|Stunting\r\n2|Normal Growth'),
(95, 1, 'PneumoniaTypes', '1|None\r\n2|Pneumonia\r\n3|Severe Pneumonia'),
(96, 1, 'VitaminTypes', '1|Cotrimoxazole\r\n2|Multivitamins\r\n3|Fluconazole \r\n4|Dapson'),
(97, 1, 'DietHistoryOptions', '1|Breakfast\r\n2|Mid-morning\r\n3|Lunch\r\n4|Mid-afternoon\r\n5|Supper'),
(98, 1, 'FoodEnrichmentOptions', '1|Add sugar\r\n2|Add oil\r\n3|Add milk  \r\n4|Fermentation   \r\n5|Salt'),
(99, 1, 'WaterSourceOptions', '1|Tap water\r\n2|River/stream\r\n3|Borehole/well\r\n4|Rain water'),
(100, 1, 'WaterPurificationOptions', '1|Boiling\r\n2|Use of chemicals (water/aqua guard)\r\n3|Water is not purified at all'),
(101, 1, 'HIVStatusTypes', '1|Positive\r\n2|Negative\r\n3|Not known'),
(102, 1, 'ARVTreatmentTypes', '1|None\r\n2|Currently on ARVs\r\n3|Has been on ARVs but stopped or defaulted'),
(103, 1, 'EnlargementTypes', '1|Not enlarged\r\n2|Enlarged'),
(104, 1, 'EyeStatusTypes', '1|Normal\r\n2|Abnormal'),
(105, 1, 'EyeStatusTypes', '1|Normal\r\n2|Abnormal'),
(106, 1, 'EnlargmentTypes', '1|Not Enlarged\r\n2|Enlarged'),
(107, 1, 'FeelTypes', '1|Soft\r\n2|Tense'),
(108, 1, 'PalpableTypes', '1|Palpable \r\n2|Impalpable'),
(109, 1, 'DirectionTypes', '1|Right \r\n2|Left'),
(110, 1, 'PenisTypes', '1|Normal \r\n2|Hypospadias'),
(111, 1, 'ConditionTypes', '1|Normal'),
(112, 1, 'DevelopmentTypes', '1|Normal\r\n2|Delayed\r\n3|child below puberty'),
(113, 1, 'MotorTypes', '1|Normal \r\n2|Delayed'),
(114, 1, 'UmbilicalTypes', '1|Large\r\n2|Moderate'),
(115, 1, 'FemaleConditionTypes', '1|Normal\r\n2|Other'),
(116, 1, 'ManagementHIVStatusTypes', '1|Positive\r\n2|Negative\r\n3|Exposed'),
(117, 1, 'SocialClientStatus', '1|Discharged\r\n2|Retested Negative\r\n3|Lost to Follow-up\r\n4|Tranfer to LTP centre'),
(118, 1, 'HIVAdultChildOptions', '1|Yes\r\n2|No\r\n3|Unknown'),
(119, 1, 'HIVCaregiverChildOptions', '1|Yes\r\n2|No\r\n3|Unknown\r\n4|ND\r\n5|No secondary caregiver identified'),
(120, 1, 'HIVCaregiverOptions', '1|Yes\r\n2|No\r\n3|Unknown\r\n4|ND'),
(121, 1, 'BirthTypes', '1|Hospital\r\n2|Home'),
(122, 1, 'TBType', '1|Abdominal\r\n2|Lymph Glands\r\n3|Bone\r\n4|Kidney'),
(123, 1, 'AdmissionReasonsNotAttendingSchool', '1|Too young\r\n2|Too ill\r\n3|Caregiver ill\r\n4|Financial reasons\r\n5|Other'),
(124, 1, 'ChildEducationLevel', '1|Pre-school\r\n2|Primary\r\n3|Secondary\r\n4|Tertiary\r\n5|Not Attending'),
(125, 1, 'LocationOptions', '1|Kangemi\r\n2|Mutuini\r\n3|Ruthimitu\r\n4|Riruta\r\n5|Waithaka\r\n6|Kawangware\r\n7|Korogocho\r\n8|Mathare\r\n9|Huruma\r\n10|Kayole\r\n11|Kiambiu\r\n12|Dandora\r\n13|Njenga\r\n14|Rueben\r\n15|Kibera A\r\n16|Kibera B\r\n\r\n'),
(126, 1, 'DeathPlaceTypes', '1|Home\r\n2|Hospital\r\n3|On way to hospital\r\n4|Other'),
(127, 1, 'PositionOptions', '1|Clinician\r\n2|Social Worker\r\n3|Counselor\r\n4|Nutritionist\r\n5|Data Entry Clerk\r\n6|Monitoring and Evaluation\r\n7|Data Manager\r\n8|Director\r\n9|Other\r\n10|CHW\r\n11|Respite'),
(128, 1, 'HIVPrimaryCaregiverOptions', '1|Positive\r\n2|Negative\r\n3|ND\r\n4|Unknown'),
(129, 1, 'CurriculumTypes', '1|National\r\n2|In-house\r\n3|Other'),
(130, 1, 'RapidResultsType', '1|Reactive\r\n2|Non-Reactive\r\n3|Indeterminate\r\n'),
(131, 1, 'ElisaResultsType', '1|Reactive \r\n2|Non-reactive \r\n3|Indeterminate\r\n'),
(132, 1, 'PCRResultsType', '1|Positive\r\n2|Negative\r\n3|Indeterminate'),
(133, 1, 'ServiceTypes', '1|A. Perm-Relocation\r\n2|B. Perm-IGA\r\n3|C. Perm-Placement\r\n4|D.  Succession Planning\r\n5|E. Legal\r\n6|F. Nursing/Palliative care\r\n7|G. Transport\r\n8|H. Education\r\n9|I. Food\r\n10|J. Rent\r\n11|K. Solidarity\r\n12|L. Direct support\r\n13|M. Medical Support\r\n14|N. Training Support'),
(134, 1, 'Enclosures', '1|Identity Card\r\n2|Med. Records\r\n3|NHIF Card\r\n4|Death Cert\r\n5|Other'),
(135, 1, 'ClientHealth', '1|Well\r\n2|Sick Looking\r\n3|Reserved'),
(136, 1, 'CaregiverPreTypes', '1|Other person\r\n2|Mother\r\n3|Father'),
(137, 1, 'TrainingSupport', '1|Hygiene\r\n2|Disclosure\r\n3|Entrepreneur skills\r\n4|Succession Planning\r\n5|Other'),
(138, 1, 'CadresTrained', '1|Clients\r\n2|Caregivers\r\n3|Staff\r\n4|CHWs\r\n5|CBCs'),
(139, 1, 'EarsOptions', '1|None\r\n2|left\r\n3|right\r\n4|both'),
(140, 1, 'ThroatOptions', '1|normal\r\n2|inflamed'),
(141, 1, 'TeethOptions', '1|Normal\r\n2|Carries'),
(142, 1, 'CNSType', '1|Normal\r\n2|Not Normal'),
(143, 1, 'ARVTreatment', '1|Start\r\n2|Continue'),
(144, 1, 'OtherDiagnoses', '1|RTI\r\n2|GIT\r\n3|ENT\r\n4|SKIN\r\n5|Malaria'),
(145, 1, 'RequestInvestigations', '1|CD4\r\n2|Viral Load\r\n3|Hb\r\n4|AST\r\n5|ATL\r\n6|X-Ray\r\n7|CT-Scan'),
(146, 1, 'TBStatus', '1|Start\r\n2|Continue\r\n3|Cured\r\n4|Change Drug\r\n5|Change Dose'),
(147, 1, 'NoYes', '1|No\r\n2|Yes'),
(148, 1, 'ChestShape', '1|Barrel chest\r\n2|Pigeon Chest\r\n3|Ricketery Rosary\r\n4|Frail Chest'),
(149, 1, 'BodySkeleton', '1|Normal\r\n2|Abnormal\r\n3|Abnormal movement'),
(150, 1, 'ChildHivAware', '1|No\r\n2|Raised w/ Caregiver\r\n3|In preparation\r\n4|New\r\n5|Already disclosed'),
(151, 1, 'SecondIdentified', '1|Yes\r\n2|No\r\n3|Process Underway'),
(152, 1, 'CounsellingReferer', '1|Social Worker\r\n2|Nutritionist\r\n3|Clinician\r\n4|MDT '),
(153, 1, 'MaritalStatusIntake', '1|Single\r\n2|Married\r\n3|Cohabiting\r\n4|Separated'),
(154, 1, 'ClientSeen', '1|Individual\r\n2|Couple'),
(155, 1, 'PositiveReferral', '1|LTP\r\n2|KNH\r\n3|KENWA\r\n4|Mbagathi Hospital\r\n5|Other'),
(156, 1, 'CD4Count', '1|Cells\r\n2|MM3\r\n3|ND'),
(157, 1, 'ClinicalReference', '1|Social worker\r\n2|Counsellor\r\n3|Nutritionist\r\n4|Respite\r\n5|MDT\r\n6|KNH\r\n7|Mbagathi\r\n8|St. Maryâ€™s \r\n9|Clinician'),
(158, 1, 'NutritionProgram', '1|Formula Milk\r\n2|Fortified blended flours\r\n3|SFP\r\n4|FBP\r\n5|RUTF'),
(159, 1, 'NutritionRendered', '1|Counseling\r\n2|Demonstration\r\n3|Dietary Supp\r\n4|Home Visit '),
(160, 1, 'FollowChildIssues', '1|none\r\n2|physical abuse\r\n3|verbal abuse\r\n4|sexual abuse\r\n5|sexual relations\r\n6|poor self-esteem  \r\n7|depression\r\n8|self-harm/suicide attempts\r\n9|alcohol/drug abuse\r\n10|other child issues'),
(161, 1, 'FollowParentIssues', '1|none\r\n2|depression\r\n3|alcohol/drug abuse\r\n4|self-harm/suicide attempts  \r\n5|unknown  \r\n6|other'),
(162, 1, 'FollowClientType', '1|child\r\n2|parent\r\n3|caregiver'),
(163, 1, 'FollowVisitType', '1|center\r\n2|home\r\n3|hospital\r\n4|school  '),
(164, 1, 'FollowServices', '1|Support\r\n2|Child\r\n3|Adherence\r\n4|Disclosure\r\n5|Preventive Education\r\n6|Other '),
(171, 1, 'WHOStage', '1|1\r\n2|2\r\n3|3\r\n4|4'),
(165, 1, 'CBCHomeCare', '1|A. Individual Counsel\r\n2|B. Grief/Bereave Counsel\r\n3|C. Spiritual Support\r\n4|D. Disclosure\r\n5|E. Link to Suppt Group/Further care'),
(166, 1, 'OldNew', '1|Old\r\n2|New'),
(167, 1, 'FollowIssues', '1|Child===FollowChildIssues\r\n2|Mother/Father===FollowParentIssues\r\n3|Caregiver===FollowParentIssues\r\n4|Disclosure\r\n5|Other close adults learn child HIV status\r\n6|Response of Disclosure\r\n7|State of Disclosure\r\n8|Secondary Caregiver knowledge\r\n9|Primary Caregiver Tested\r\n10|Mother/Father Status\r\n11|M/F/C Treatment\r\n12|Stigmatization\r\n13|Secondary Caregiver Identification'),
(168, 1, 'CrepitationTypes', '1|crepitations\r\n2|rhonchi\r\n3|trans sounds\r\n4|other  '),
(169, 1, 'SkinOptions', '1|ppe\r\n2|herpes zoster\r\n3|chicken pox\r\n4|measles\r\n5|others'),
(170, 1, 'TherapyStage', '1|1st line\r\n2|2nd line\r\n3|Salvage'),
(172, 1, 'ClinicalStage', '1|1\r\n2|2\r\n3|3'),
(173, 1, 'Grades', '1|mild\r\n2|moderate\r\n3|severe'),
(174, 1, 'AdherenceSupport', '1|A. Self Report\r\n2|B. Pill Count\r\n3|C. Side Effects\r\n4|D. Away from Home '),
(175, 1, 'VisitMode', '1|Follow up\r\n2|Visit');
-- ------------------------------------------------
  CREATE TABLE IF NOT EXISTS `queries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `qname` varchar(255) NOT NULL,
  `qdesc` text NOT NULL,
  `sdate` int(8) NOT NULL DEFAULT '0',
  `edate` int(8) NOT NULL DEFAULT '0',
  `visits` enum('all','last','first') NOT NULL DEFAULT 'all',
  `fils` text NOT NULL,
  `posts` text NOT NULL,
  `visible` enum('0','1') NOT NULL DEFAULT '1',
  `actives` enum('0','1') NOT NULL DEFAULT '0',
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;
-- ----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stat_queries` (
  `id` int(12) NOT NULL AUTO_INCREMENT,
  `qname` varchar(255) NOT NULL DEFAULT '',
  `qdesc` text NOT NULL,
  `rows` text NOT NULL,
  `cols` text NOT NULL,
  `ranges` text NOT NULL,
  `turns` varchar(100) NOT NULL,
  `sdate` int(8) NOT NULL,
  `edate` int(8) NOT NULL,
  `show_result` enum('0','1') NOT NULL DEFAULT '1',
  `query_id` int(12) NOT NULL DEFAULT '0',
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;
-- -------------------------------------------------------
update clients, admission_info set client_gender= admission_gender where admission_client_id=client_id;
-- ------------------------------------------------
update counselling_info, admission_info set counselling_admission_date=admission_entry_date,admission_total_orphan=counselling_total_orphan where admission_client_id=counselling_client_id;
-- ---------------------------------------------
update counselling_info, clients set client_dob=counselling_dob,client_doa=counselling_admission_date where client_id=counselling_client_id;
-- --------------------------------------------
rename table social_visit to social_visit_old, social_visit_slim to social_visit; 
-- -------------------------------------------
alter table activity add activity_end_date DATE default null;
-- ------------------------------------------------
 update activity set activity_end_date = activity_date; 
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `status_client` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `social_client_id` int(10) NOT NULL,
  `social_client_status` int(10) DEFAULT NULL,
  `social_entry_date` date DEFAULT NULL,
  `mode` enum('status','center') NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;
-- ----------------------------------------------------------
update contacts set contact_id='13' where contact_last_name="-Select Staff-";
-- -----------------------------------------------------------

CREATE TABLE IF NOT EXISTS `admission_caregivers_staging` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `new_id` int(11) unsigned NOT NULL,
  `fname` varchar(100) DEFAULT NULL,
  `lname` varchar(100) DEFAULT NULL,
  `age` varchar(10) DEFAULT NULL,
  `health_status` tinyint(1) unsigned DEFAULT "0",
  `marital_status` tinyint(2) unsigned DEFAULT "0",
  `educ_level` tinyint(2) unsigned NOT NULL DEFAULT "0",
  `employment` tinyint(2) unsigned NOT NULL DEFAULT "0",
  `idno` varchar(100) NOT NULL DEFAULT "",
  `mobile` varchar(50) NOT NULL DEFAULT "",
  `client_adm_no` varchar(50) DEFAULT NULL,
  `client_first_name` varchar(100) DEFAULT NULL,
  `client_other_name` varchar(100) DEFAULT NULL,
  `client_last_name` varchar(100) DEFAULT NULL,
  `client_id` INT( 11 ) NULL DEFAULT NULL ,
  `reason` tinyint(2) unsigned DEFAULT NULL,
  `datesoff` date DEFAULT NULL,
  `role` enum("mother","father","pri","sec") DEFAULT NULL,
  `relationship` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `role` (`role`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 ;
-- --------------------------------------------------

alter table activities_staging
	add `activity_custom` longtext,
 	add `activity_hpd` float unsigned NOT NULL,
	add `activity_visiters_total` int(10) DEFAULT NULL,
	add `activity_cadres` varchar(30) DEFAULT NULL,
	add `activity_end_date` date DEFAULT NULL,
	ADD `activity_id` INT( 11 ) UNSIGNED NULL DEFAULT NULL FIRST;

alter table `activity_caregivers_staging` add `caregiver_role` enum("mother","father","pri","sec") DEFAULT NULL;
	
ALTER TABLE `files` ADD `file_imported` ENUM( '0', '1' ) NOT NULL;

-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `followup_info_staging` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `followup_client_id` int(11) DEFAULT NULL,
  `client_adm_no` varchar(50) DEFAULT NULL,
  `client_first_name` varchar(100) DEFAULT '',
  `client_other_name` varchar(100) DEFAULT '',
  `client_last_name` varchar(100) DEFAULT '',
  `followup_adm_no` varchar(20) NOT NULL,
  `followup_client_type` tinyint(1) DEFAULT NULL,
  `followup_object` varchar(100) DEFAULT NULL,
  `followup_visit_type` tinyint(1) DEFAULT NULL,
  `followup_issues` varchar(150) DEFAULT NULL,
  `followup_issues_notes` varchar(150) DEFAULT NULL,
  `followup_service` varchar(50) DEFAULT NULL,
  `followup_service_notes` varchar(150) DEFAULT NULL,
  `followup_date` date DEFAULT NULL,
  `followup_center_id` int(11) DEFAULT NULL,
  `clinic_name` varchar(100) DEFAULT '',
  `followup_officer_id` int(11) DEFAULT NULL,
  `followup_staff_name` varchar(100) DEFAULT NULL,
  `followup_visit_mode` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
-- -------------------------------------------

CREATE TABLE IF NOT EXISTS `cbc_info_staging` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `cbc_client_id` int(11) DEFAULT NULL,
  `client_adm_no` varchar(50) DEFAULT NULL,
  `client_first_name` varchar(100) DEFAULT '',
  `client_other_name` varchar(100) DEFAULT '',
  `client_last_name` varchar(100) DEFAULT '',
  `cbc_name` varchar(100) DEFAULT NULL,
  `cbc_village` varchar(100) DEFAULT NULL,
  `cbc_center_id` int(10) DEFAULT NULL,
  `clinic_name` varchar(100) DEFAULT '',
  `cbc_location` varchar(100) DEFAULT NULL,
  `cbc_entry_date` date DEFAULT NULL,
  `cbc_adm_no` varchar(30) DEFAULT NULL,
  `cbc_old` tinyint(1) DEFAULT NULL,
  `cbc_sex` tinyint(1) DEFAULT NULL,
  `cbc_age` varchar(10) DEFAULT NULL,
  `cbc_hbcare` varchar(50) DEFAULT NULL,
  `cbc_adh_support` tinyint(1) DEFAULT NULL,
  `cbc_remarks` text,
  `cbc_refers` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
-- ---------------------------------------------
CREATE TABLE IF NOT EXISTS `chw_info_staging` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `chw_client_id` int(11) DEFAULT NULL,
  `client_adm_no` varchar(50) DEFAULT NULL,
  `client_first_name` varchar(100) DEFAULT '',
  `client_other_name` varchar(100) DEFAULT '',
  `client_last_name` varchar(100) DEFAULT '',
  `chw_name` varchar(100) DEFAULT NULL,
  `chw_center_id` int(11) DEFAULT NULL,
  `clinic_name` varchar(100) DEFAULT '',
  `chw_village` varchar(100) DEFAULT NULL,
  `chw_location` varchar(100) DEFAULT NULL,
  `chw_entry_date` date DEFAULT NULL,
  `chw_adm_no` varchar(30) DEFAULT NULL,
  `chw_sex` tinyint(1) DEFAULT NULL,
  `chw_old` tinyint(1) DEFAULT NULL,
  `chw_age` varchar(5) DEFAULT NULL,
  `chw_hasplan` tinyint(1) DEFAULT NULL,
  `chw_arv` tinyint(1) DEFAULT NULL,
  `chw_arv_note` tinyint(1) DEFAULT NULL,
  `chw_oir` tinyint(1) DEFAULT NULL,
  `chw_oir_note` varchar(100) DEFAULT NULL,
  `chw_tb` tinyint(1) DEFAULT NULL,
  `chw_nutrition` text,
  `chw_adh_support` int(11) DEFAULT NULL,
  `chw_assess` varchar(50) DEFAULT NULL,
  `chw_support` varchar(50) DEFAULT NULL,
  `chw_comm_mob` varchar(50) DEFAULT NULL,
  `chw_refers` text,
  `chw_remarks` text,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
